name: fontsy_fonter_font_switcher
description: "A small app to show how to use fonts"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.2.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster_two/LobsterTwo-Bold.ttf
        - asset: assets/fonts/lobster_two/LobsterTwo-BoldItalic.ttf
        - asset: assets/fonts/lobster_two/LobsterTwo-Italic.ttf
        - asset: assets/fonts/lobster_two/LobsterTwo-Regular.ttf
    - family: Noto Mono
      fonts:
        - asset: assets/fonts/NotoSansMono-VariableFont.ttf

